In [1]:
import pandas as pd

In [ ]:
#reading raw csv file
lhb_df = pd.read_csv(r"C:\Users\LENOVO\Documents\Luxury_Housing_BLR\Luxury_Housing_Bangalore.csv")

In [ ]:
#knowing the size of the dataset
lhb_df.shape

(101000, 18)

In [ ]:
#coloumn names
lhb_df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

In [ ]:
#coloumn type
lhb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [ ]:
#Table statistics
lhb_df.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [ ]:
#no of duplicate rows
lhb_df.duplicated().sum()

np.int64(1000)

In [ ]:
#no of null values
lhb_df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [ ]:
#Percentage of null values
(lhb_df.isnull().sum() / len(lhb_df)) * 100

Property_ID              0.000000
Micro_Market             0.000000
Project_Name             0.000000
Developer_Name           0.000000
Unit_Size_Sqft           9.946535
Configuration            0.000000
Ticket_Price_Cr          9.919802
Transaction_Type         0.000000
Buyer_Type               0.000000
Purchase_Quarter         0.000000
Connectivity_Score       0.000000
Amenity_Score            9.990099
Possession_Status        0.000000
Sales_Channel            0.000000
NRI_Buyer                0.000000
Locality_Infra_Score     0.000000
Avg_Traffic_Time_Min     0.000000
Buyer_Comments          18.105941
dtype: float64

In [ ]:
#duplicate values in property id
lhb_df["Property_ID"].duplicated().sum()

np.int64(1000)

In [ ]:
#
lhb_df["Property_ID"].duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
100995     True
100996     True
100997     True
100998     True
100999     True
Name: Property_ID, Length: 101000, dtype: bool

In [ ]:
#total unique values in property id
lhb_df["Property_ID"].nunique()

100000

In [ ]:
#length of raw dataset
len(lhb_df)

101000

In [ ]:
#value counts of transaction type
lhb_df["Transaction_Type"].value_counts()

Transaction_Type
Secondary    50506
Primary      50494
Name: count, dtype: int64

In [ ]:
#value counts of buyer type
lhb_df["Buyer_Type"].value_counts()

Buyer_Type
CXO                20340
NRI                20207
Startup Founder    20185
Other              20149
HNI                20119
Name: count, dtype: int64

In [ ]:
#total rows in buyer type
lhb_df["Buyer_Type"].value_counts().sum()

np.int64(101000)

In [ ]:
#total values for each configuration type
lhb_df["Configuration"].value_counts()

Configuration
5Bhk+    11375
3Bhk     11332
5BHK+    11291
3bhk     11262
5bhk+    11210
4bhk     11173
4Bhk     11151
3BHK     11136
4BHK     11070
Name: count, dtype: int64

In [ ]:
#total values for each possession status
lhb_df["Possession_Status"].value_counts()

Possession_Status
Under construction    33769
Launch                33641
Ready to move         33590
Name: count, dtype: int64

In [ ]:
#total values for each sales channel
lhb_df["Sales_Channel"].value_counts()

Sales_Channel
Online      25411
Broker      25385
NRI Desk    25271
Direct      24933
Name: count, dtype: int64

In [ ]:
#total values for each NRI buyer status
lhb_df["NRI_Buyer"].value_counts()

NRI_Buyer
no     50516
yes    50484
Name: count, dtype: int64

In [ ]:
#total values for each purchase quarter
lhb_df["Purchase_Quarter"].value_counts()

Purchase_Quarter
31-03-2024    12750
30-09-2024    12683
30-06-2023    12655
30-09-2023    12618
30-06-2024    12608
31-12-2024    12595
31-12-2023    12560
31-03-2025    12531
Name: count, dtype: int64

In [ ]:
#Purchase quarter data type
lhb_df["Purchase_Quarter"].dtype

dtype('O')

In [ ]:
#Unit size description
lhb_df["Unit_Size_Sqft"].describe()

count    90954.000000
mean      5972.274765
std       1783.397836
min         -1.000000
25%       4477.250000
50%       5990.000000
75%       7497.000000
max       8999.000000
Name: Unit_Size_Sqft, dtype: float64

In [ ]:
#finding negetive place
lhb_df[lhb_df["Unit_Size_Sqft"] == -1].shape

(505, 18)

In [ ]:
#null values in unit sq feet
lhb_df[lhb_df["Unit_Size_Sqft"].isnull()]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
17,PROP000018,YELAHANKA,Project_17,L&T Realty,NaN,4BHK,9.045289663,Secondary,CXO,31-03-2024,8.793448,5.186328,Ready to move,NRI Desk,yes,9.256085,77,Loved the amenities!
18,PROP000019,YELAHANKA,Project_18,Total Environment,NaN,5Bhk+,7.623657466,Primary,Other,31-12-2024,6.111031,6.898634,Ready to move,Broker,yes,8.652232,118,Connectivity is poor.
24,PROP000025,Mg Road,Project_24,L&T Realty,NaN,3Bhk,₹13.64 Cr,Primary,Other,31-03-2024,9.300782,9.464122,Under construction,Online,no,8.127972,43,Agent was not responsive.
33,PROP000034,jp nagar,Project_33,Tata Housing,NaN,5bhk+,15.01877994,Primary,CXO,30-09-2024,7.991544,5.489478,Ready to move,Direct,yes,6.337526,64,Great value for money.
45,PROP000046,Mg Road,Project_45,Brigade,NaN,5bhk+,15.67178253,Primary,NRI,31-12-2023,8.186105,9.515085,Launch,NRI Desk,yes,5.414198,57,Agent was not responsive.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100946,PROP068368,rajajinagar,Project_367,Sobha,NaN,5BHK+,10.02517751,Secondary,NRI,31-12-2023,8.567535,5.013950,Under construction,NRI Desk,yes,6.705184,15,Loved the amenities!
100953,PROP068005,Mg Road,Project_4,Total Environment,NaN,3BHK,6.719054771,Secondary,Startup Founder,31-12-2023,9.345955,8.484690,Under construction,Broker,no,9.250374,104,Loved the amenities!
100958,PROP057589,bellary road,Project_88,RMZ,NaN,5BHK+,10.42667813,Primary,NRI,31-12-2024,8.000070,8.857594,Under construction,NRI Desk,yes,9.588207,95,Too far from my office.
100966,PROP084077,Jayanagar,Project_76,Prestige,NaN,4Bhk,14.49062859,Primary,HNI,30-06-2023,7.193573,5.904934,Ready to move,Direct,no,5.996074,113,Great value for money.
100992,PROP064846,kanakapura road,Project_345,Prestige,NaN,3bhk,12.46795503,Secondary,HNI,31-12-2023,6.047293,9.163434,Launch,Broker,no,7.544191,78,Excellent location!

In [ ]:
#Ticket price description
lhb_df["Ticket_Price_Cr"].describe()

count     90981
unique    72852
top         100
freq        278
Name: Ticket_Price_Cr, dtype: object

In [28]:
lhb_df["Ticket_Price_Cr"].head(20)

0     12.75084604
1     16.29215187
2     10.51772441
3     9.396367494
4     15.34539244
5        ₹9.82 Cr
6     10.89675235
7     9.357538944
8     12.29944941
9     9.193310279
10    15.22182382
11    7.384787239
12     11.0424633
13    15.16628527
14    13.85156318
15             70
16    9.750864805
17    9.045289663
18    7.623657466
19    9.627966273
Name: Ticket_Price_Cr, dtype: object

In [ ]:
#toatlly how many values are there in rupees and crores
lhb_df["Ticket_Price_Cr"].astype(str).str.contains("₹|Cr", na=False).sum()

np.int64(18211)

In [ ]:
#Total values for each ticket price configuration
lhb_df[lhb_df["Ticket_Price_Cr"].astype(str).str.contains("₹|Cr", na=False)]["Ticket_Price_Cr"].value_counts().head(20)

Ticket_Price_Cr
₹100.0 Cr    73
₹70.0 Cr     64
₹60.0 Cr     56
₹11.71 Cr    41
₹12.63 Cr    36
₹11.04 Cr    35
₹10.48 Cr    35
₹11.56 Cr    34
₹12.0 Cr     34
₹10.37 Cr    34
₹12.24 Cr    33
₹10.65 Cr    33
₹11.08 Cr    32
₹12.07 Cr    32
₹11.9 Cr     32
₹14.08 Cr    32
₹13.09 Cr    31
₹14.03 Cr    31
₹12.28 Cr    31
₹11.5 Cr     31
Name: count, dtype: int64

In [ ]:
#Amenity score description
lhb_df["Amenity_Score"].describe()

count    90910.000000
mean         7.503663
std          1.440758
min          5.000224
25%          6.260329
50%          7.499123
75%          8.752207
max          9.999865
Name: Amenity_Score, dtype: float64

In [ ]:
#Connectivity score description
lhb_df["Connectivity_Score"].describe()

count    101000.000000
mean          6.992619
std           1.731757
min           4.000031
25%           5.494526
50%           6.985805
75%           8.490000
max           9.999970
Name: Connectivity_Score, dtype: float64

In [ ]:
#Locality infrastructure score description
lhb_df["Locality_Infra_Score"].describe()

count    101000.000000
mean          7.498426
std           1.443128
min           5.000013
25%           6.247954
50%           7.495614
75%           8.749824
max           9.999956
Name: Locality_Infra_Score, dtype: float64

In [ ]:
#Average traffic time description
lhb_df["Avg_Traffic_Time_Min"].describe()

count    101000.000000
mean         67.182921
std          30.271611
min          15.000000
25%          41.000000
50%          67.000000
75%          93.000000
max         119.000000
Name: Avg_Traffic_Time_Min, dtype: float64

In [35]:
#write all the coloumns and what need to be done for data cleaning process

In [36]:
clean_df = lhb_df.copy()

In [37]:
clean_df.duplicated().sum()

np.int64(1000)

In [38]:
clean_df = clean_df.drop_duplicates()

In [39]:
clean_df.duplicated().sum()

np.int64(0)

In [40]:
clean_df["Property_ID"].duplicated().sum()

np.int64(0)

In [41]:
clean_df["Micro_Market"].value_counts()

Micro_Market
Jayanagar            2157
Bannerghatta Road    2148
mg road              2144
Jp Nagar             2143
bannerghatta road    2137
jp nagar             2136
sarjapur road        2135
indiranagar          2127
SARJAPUR ROAD        2125
domlur               2124
WHITEFIELD           2124
jayanagar            2119
Sarjapur Road        2113
JAYANAGAR            2103
bellary road         2101
Electronic City      2099
MG ROAD              2098
JP NAGAR             2094
hennur road          2091
yelahanka            2090
BANNERGHATTA ROAD    2089
Kanakapura Road      2088
kanakapura road      2088
Yelahanka            2087
Hebbal               2083
Indiranagar          2078
RAJAJINAGAR          2077
Whitefield           2073
whitefield           2071
Rajajinagar          2070
ELECTRONIC CITY      2070
BELLARY ROAD         2062
rajajinagar          2060
KANAKAPURA ROAD      2059
INDIRANAGAR          2058
Hennur Road          2057
KORAMANGALA          2052
Bellary Road         2052
HEBBAL               2049
DOMLUR               2049
electronic city      2043
Mg Road              2042
hebbal               2040
YELAHANKA            2036
Koramangala          2024
koramangala          2017
HENNUR ROAD          2010
Domlur               2008
Name: count, dtype: int64

In [ ]:
#Changing all the values in micro market to upper case for consistency
clean_df["Micro_Market"] = clean_df["Micro_Market"].str.upper()

In [ ]:
#Total values for each micro market
clean_df["Micro_Market"].value_counts()

Micro_Market
JAYANAGAR            6379
BANNERGHATTA ROAD    6374
JP NAGAR             6373
SARJAPUR ROAD        6373
MG ROAD              6284
WHITEFIELD           6268
INDIRANAGAR          6263
KANAKAPURA ROAD      6235
BELLARY ROAD         6215
YELAHANKA            6213
ELECTRONIC CITY      6212
RAJAJINAGAR          6207
DOMLUR               6181
HEBBAL               6172
HENNUR ROAD          6158
KORAMANGALA          6093
Name: count, dtype: int64

In [ ]:
#Changing Configuration values to upper case 
clean_df["Configuration"] = clean_df["Configuration"].str.upper()

In [ ]:
#Total values for each configuration
clean_df["Configuration"].value_counts()

Configuration
5BHK+    33536
3BHK     33377
4BHK     33087
Name: count, dtype: int64

In [ ]:
#clean_df.to_csv("Luxury_Housing_Bangalore_cleaning_checkpoint.csv", index=False)

In [47]:
clean_df["Ticket_Price_Cr"].dtype

dtype('O')

In [ ]:
#removing ₹ 
clean_df["Ticket_Price_Cr"] = clean_df["Ticket_Price_Cr"].str.replace("₹", "")

In [ ]:
#removing "Cr"
clean_df["Ticket_Price_Cr"] = clean_df["Ticket_Price_Cr"].str.replace(" Cr", "")

In [ ]:
#converting to float
clean_df["Ticket_Price_Cr"] = pd.to_numeric(clean_df["Ticket_Price_Cr"], errors="coerce")

In [51]:
clean_df["Ticket_Price_Cr"].dtype

dtype('float64')

In [52]:
clean_df["Ticket_Price_Cr"].head(20)

0     12.750846
1     16.292152
2     10.517724
3      9.396367
4     15.345392
5      9.820000
6     10.896752
7      9.357539
8     12.299449
9      9.193310
10    15.221824
11     7.384787
12    11.042463
13    15.166285
14    13.851563
15    70.000000
16     9.750865
17     9.045290
18     7.623657
19     9.627966
Name: Ticket_Price_Cr, dtype: float64

In [ ]:
#total null values in ticket price
clean_df["Ticket_Price_Cr"].isnull().sum()

np.int64(9913)

In [ ]:
clean_df.loc[clean_df["Ticket_Price_Cr"].isnull(),"Ticket_Price_Cr"].head(20)

26    NaN
40    NaN
43    NaN
51    NaN
53    NaN
64    NaN
90    NaN
114   NaN
129   NaN
134   NaN
136   NaN
148   NaN
152   NaN
160   NaN
162   NaN
166   NaN
171   NaN
175   NaN
194   NaN
197   NaN
Name: Ticket_Price_Cr, dtype: float64

In [ ]:
#Storing the values of null value index
bad_index = clean_df.index[clean_df["Ticket_Price_Cr"].isnull()]

In [ ]:
lhb_df.loc[bad_index, "Ticket_Price_Cr"].value_counts().head(20)

Series([], Name: count, dtype: int64)

In [ ]:
#Total null values in the ticket price 
clean_df["Ticket_Price_Cr"].isnull().sum()

np.int64(9913)

In [ ]:
clean_df["Ticket_Price_Cr"].describe()

count    90087.000000
mean        12.719069
std          7.670383
min         -1.420000
25%         10.010969
50%         12.038456
75%         14.097009
max        100.000000
Name: Ticket_Price_Cr, dtype: float64

In [ ]:
#Negative values in Ticket price
clean_df[clean_df["Ticket_Price_Cr"] < 0]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
3645,PROP003646,INDIRANAGAR,Project_145,Embassy,5092.0,4BHK,-0.391623,Primary,Startup Founder,30-06-2024,7.149634,6.123946,Under construction,Direct,no,6.967136,105,Too far from my office.
6130,PROP006131,HENNUR ROAD,Project_130,RMZ,4019.0,5BHK+,-1.420000,Primary,Startup Founder,30-06-2023,6.344294,6.345932,Launch,Direct,no,5.137908,40,Underpriced for location.
39358,PROP039359,HEBBAL,Project_358,Tata Housing,4924.0,5BHK+,-0.287197,Primary,NRI,30-09-2023,4.167448,NaN,Ready to move,NRI Desk,yes,8.249373,115,NaN
50185,PROP050186,JP NAGAR,Project_185,Godrej,5807.0,5BHK+,-0.193873,Primary,CXO,31-12-2024,5.707500,9.986799,Launch,Broker,no,7.867063,73,Excellent location!
83801,PROP083802,HEBBAL,Project_301,Tata Housing,6548.0,3BHK,-0.519437,Primary,HNI,31-03-2025,9.180127,7.053654,Under construction,Broker,no,8.870240,87,Great view from 15th floor.

In [ ]:
#converting negative values to NaN in ticket price column
import numpy as np
clean_df.loc[clean_df["Ticket_Price_Cr"] < 0, "Ticket_Price_Cr"] = np.nan

In [ ]:
#checking the null values in ticket price column after converting negative values to NaN
clean_df["Ticket_Price_Cr"].isnull().sum()

np.int64(9918)

In [ ]:
#first 5 rows of the null values in ticket price column after converting negative values to NaN
clean_df[clean_df["Ticket_Price_Cr"].isnull()].head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
26,PROP000027,JAYANAGAR,Project_26,Godrej,7366.0,5BHK+,NaN,Primary,Startup Founder,30-06-2023,7.350917,8.447686,Launch,NRI Desk,yes,9.032851,105,Loved the amenities!
40,PROP000041,KORAMANGALA,Project_40,Godrej,7987.0,3BHK,NaN,Primary,CXO,30-09-2023,6.981554,5.087539,Ready to move,Online,yes,7.197818,72,Connectivity is poor.
43,PROP000044,ELECTRONIC CITY,Project_43,SNN Raj,7659.0,3BHK,NaN,Secondary,NRI,31-12-2023,6.180085,7.565496,Ready to move,NRI Desk,no,5.365011,34,Too far from my office.
51,PROP000052,HENNUR ROAD,Project_51,L&T Realty,3163.0,4BHK,NaN,Secondary,HNI,31-12-2023,6.697532,7.002979,Launch,Broker,yes,5.617320,56,Great value for money.
53,PROP000054,MG ROAD,Project_53,Sobha,7849.0,3BHK,NaN,Secondary,CXO,31-03-2025,8.480134,9.820831,Launch,Online,no,5.609900,55,Underpriced for location.

In [ ]:
#negative values in unit size column
(clean_df["Unit_Size_Sqft"] < 0).sum()

np.int64(500)

In [ ]:
#Negative value and how many of them
clean_df[clean_df["Unit_Size_Sqft"] < 0]["Unit_Size_Sqft"].value_counts()

Unit_Size_Sqft
-1.0    500
Name: count, dtype: int64

In [ ]:
#converting negative values to NaN in unit size column
import numpy as np
clean_df.loc[clean_df["Unit_Size_Sqft"] <= 0, "Unit_Size_Sqft"] = np.nan

In [ ]:
#total null values in unit size column after converting negative values to NaN
clean_df["Unit_Size_Sqft"].isnull().sum()

np.int64(10457)

In [ ]:
#median unit size for each configuration
clean_df.groupby("Configuration")["Unit_Size_Sqft"].median()

Configuration
3BHK     5996.5
4BHK     6007.0
5BHK+    6010.0
Name: Unit_Size_Sqft, dtype: float64

In [ ]:
#Filling median values for null values in unit size column based on configuration
clean_df["Unit_Size_Sqft"] = clean_df.groupby("Configuration")["Unit_Size_Sqft"].transform(lambda x: x.fillna(x.median()))

In [ ]:
#checking null values in unit size 
clean_df["Unit_Size_Sqft"].isnull().sum()

np.int64(0)

In [ ]:
#checking null values in Amenity score column
clean_df["Amenity_Score"].isnull().sum()

np.int64(10000)

In [ ]:
#checking the median value of Amenity score
clean_df["Amenity_Score"].median()

np.float64(7.499766492)

In [ ]:
#Filling null values with median value in Amenity score column
clean_df["Amenity_Score"] = clean_df["Amenity_Score"].fillna(clean_df["Amenity_Score"].median())

In [ ]:
#checking null values in Amenity score column
clean_df["Amenity_Score"].isnull().sum()

np.int64(0)

In [ ]:
#checking null values in Buyer comments column
clean_df["Buyer_Comments"].isnull().sum()

np.int64(18099)

In [ ]:
#Filling empty values in Buyer comments column with "data_not_given"
clean_df["Buyer_Comments"] = clean_df["Buyer_Comments"].fillna("data_not_given")

In [ ]:
#checking null values in Buyer comments column
clean_df["Buyer_Comments"].isnull().sum()

np.int64(0)

In [ ]:
#checking null values in all the coloumns
clean_df.isnull().sum()

Property_ID                0
Micro_Market               0
Project_Name               0
Developer_Name             0
Unit_Size_Sqft             0
Configuration              0
Ticket_Price_Cr         9913
Transaction_Type           0
Buyer_Type                 0
Purchase_Quarter           0
Connectivity_Score         0
Amenity_Score              0
Possession_Status          0
Sales_Channel              0
NRI_Buyer                  0
Locality_Infra_Score       0
Avg_Traffic_Time_Min       0
Buyer_Comments             0
dtype: int64

In [ ]:
#Checking Duplicate IDs
clean_df["Property_ID"].duplicated().sum()

np.int64(0)

In [ ]:
clean_df.shape

(100000, 18)

In [ ]:
clean_df.dtypes

Property_ID              object
Micro_Market             object
Project_Name             object
Developer_Name           object
Unit_Size_Sqft          float64
Configuration            object
Ticket_Price_Cr         float64
Transaction_Type         object
Buyer_Type               object
Purchase_Quarter         object
Connectivity_Score      float64
Amenity_Score           float64
Possession_Status        object
Sales_Channel            object
NRI_Buyer                object
Locality_Infra_Score    float64
Avg_Traffic_Time_Min      int64
Buyer_Comments           object
dtype: object

In [80]:
import sys
print(sys.executable)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\python.exe

In [81]:
import openpyxl
print(openpyxl.__version__)

3.1.5

In [83]:
clean_df.to_excel("Luxury_Housing_Cleanedo.xlsx", index=False)

In [ ]:
#After detecting null values , filled those values with median values
#filled null values in buyer comments with "data_not_given"
#9913 null values in ticket price column
#(100000 , 18) CSV file size